Update android-build.yml

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -7,7 +7,6 @@ on:
   pull_request:
     branches:
       - main
-      
 
 jobs:
   build:
@@ -16,6 +15,12 @@ jobs:
     steps:
     - name: Checkout repo
       uses: actions/checkout@v3
+
+    - name: List root files for debug
+      run: ls -l
+
+    - name: List gradle wrapper files for debug
+      run: ls -l gradle/wrapper || echo "gradle/wrapper folder missing"
 
     - name: Set up JDK 11
       uses: actions/setup-java@v3
